"""New Migration3

Revision ID: 06bbcd3dde28
Revises: 2b99d6140659
Create Date: 2023-12-19 15:01:39.478136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06bbcd3dde28'
down_revision: Union[str, None] = '2b99d6140659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('shiftreport_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'shiftreport_id')
    # ### end Alembic commands ###
