"""New Migration2

Revision ID: 2b99d6140659
Revises: 303f96c9c40b
Create Date: 2023-12-19 11:59:54.929985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b99d6140659'
down_revision: Union[str, None] = '303f96c9c40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payrun', sa.Column('total_remittance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payrun', 'total_remittance')
    # ### end Alembic commands ###
