"""New Migration1

Revision ID: 303f96c9c40b
Revises: f4beb071f2d0
Create Date: 2023-12-19 11:40:32.592803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303f96c9c40b'
down_revision: Union[str, None] = 'f4beb071f2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('remittance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'remittance')
    # ### end Alembic commands ###
