"""New Migration3

Revision ID: df4cec299669
Revises: 06bbcd3dde28
Create Date: 2024-01-27 16:37:58.832119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4cec299669'
down_revision: Union[str, None] = '06bbcd3dde28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('serviceType', sa.String(), nullable=True))
    op.add_column('invoice', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'notes')
    op.drop_column('invoice', 'serviceType')
    # ### end Alembic commands ###
